### ISSUE TITLE
Feat: Add shortcut for navigation to previous view

### ISSUE THREAD

**Issue by Christopher-Hayes** [ubuntu/app-center#1860]
## Description

Browsers and apps in general will support the keyboard shortcut, <kbd>Alt</kbd> + <kbd>Left Arrow</kbd>, for returning the user to the previous page.

I have a dedicated mouse button for this, I believe it just emulates that keyboard combination. Currently, App Center does not do anything when I try <kbd>Alt</kbd> + <kbd>Left Arrow</kbd> or use my mouse's back button. This is a shortcut that was supported on the old software app.

**Feature request** - support the <kbd>Alt</kbd> + <kbd>Left Arrow</kbd> keyboard shortcut for backwards navigation.

## Current Behavior

1. Navigate to an app page.
2. Press <kbd>Alt</kbd> + <kbd>Left Arrow</kbd>
3. Nothing happens.

## Desired Behavior

1. Navigate to an app page.
2. Press <kbd>Alt</kbd> + <kbd>Left Arrow</kbd>
3. The view should bring you back to the previous page you were looking at.

## Shortcuts

<kbd>Alt</kbd> + <kbd>Left Arrow</kbd> would be the most popular I think.

<kbd>Alt</kbd> + <kbd>Right Arrow</kbd> could be added for forward navigation, but I would expect this shortcut to be used a lot less.

### For reference

GNOME Standard Keyboard Shortcut guidelines for navigation: https://developer.gnome.org/hig/reference/keyboard.html

## App details

```yaml
name:    snap-store
summary: Snap Store is a graphical desktop application for discovering,
  installing and managing snaps on Linux.
publisher: Canonical✓
store-url: https://snapcraft.io/snap-store
contact:   https://bugs.launchpad.net/snap-store/
license:   unset
description: |
  Snap Store showcases featured and popular applications with useful
  descriptions, ratings, reviews and screenshots.


  Applications can be found either through browsing categories
  or by searching.


  Snap Store can also be used to switch channels, view and alter snap
  permissions and view and submit reviews and ratings.


  Snap Store is based on GNOME Software, optimized for the Snap experience.
commands:
  - snap-store.show-updates
  - snap-store
snap-id:      gjf3IPXoRiipCu9K0kVu52f0H56fIksg
tracking:     2/stable/ubuntu-24.10
refresh-date: 46 days ago, at 11:48 EDT
channels:
  2/stable:          0+git.4fcd62b7   2024-09-19 (1218) 11MB -
  2/candidate:       ↑
  2/beta:            ↑
  2/edge:            0+git.b2772108   2024-10-23 (1238) 11MB -
  latest/stable:     41.3-72-g80e7130 2024-09-22 (1216) 12MB -
  latest/candidate:  ↑
  latest/beta:       ↑
  latest/edge:       0+git.b2772108   2024-10-23 (1238) 11MB -
  preview/stable:    –
  preview/candidate: 0.2.7-alpha      2023-02-02  (864) 10MB -
  preview/beta:      ↑
  preview/edge:      0.3.0-alpha      2023-08-14 (1017) 11MB -
  1/stable:          41.3-72-g80e7130 2024-09-22 (1216) 12MB -
  1/candidate:       ↑
  1/beta:            ↑
  1/edge:            41.3-72-g80e7130 2024-09-16 (1216) 12MB -
installed:           0+git.4fcd62b7              (1218) 11MB -
```
